In [14]:
#!pip install numpy

In [15]:
import numpy as np

In [16]:
import pandas as pd

In [17]:
#**Q1.1:** Create a 4x4 identity matrix using `np.eye()`
identity_matrix=np.eye(4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
#**Q1.2:** Create an array of 8 zeros using `np.zeros()`
array=np.zeros(8)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [19]:

#**Q1.3:** Create an array of 6 ones using `np.ones()`
array=np.ones(6)
print(array)

[1. 1. 1. 1. 1. 1.]


In [20]:
#**Q1.4:** Create an array with values from 0 to 15 using `np.arange()`
array=np.arange(15)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [24]:
#Create an array with 8 evenly spaced values from 0 to 100 using `np.linspace()`
array=np.linspace(0,100,8)
print(array)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [22]:
### Question 2: Array Attributes and Information

In [113]:
#**Q2.1:** What is the shape of the `banking_data` array?
bank_data.shape

(10, 5)

In [5]:
import numpy as np
bank_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])
bank_data

array([[    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]])

In [114]:
a=np.random.randint(1,5,(3,3))

In [ ]:
bank_data

array([[    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]])

In [ ]:
#("**Q2.2:** What is the data type of the `banking_data` array?")
import numpy as np
bank_data.dtype

dtype('int64')

In [ ]:
#**Q2.3:** What is the size (total number of elements) of the `banking_data` array?
bank_data.size

50

In [ ]:
#**Q2.4:** What is the number of dimensions of the `banking_data` array?
bank_data.ndim


2

In [ ]:
#**Q2.5:** What is the memory size of the `banking_data` array in bytes?
bank_data.nbytes

400

In [ ]:
### Question 3: Indexing and Slicing

In [ ]:
#**Q3.1:** Extract the first row of `banking_data`
bank_data
bank_data[0]


array([    1, 25000,   300,  1200,    10])

In [ ]:
#**Q3.2:** Extract the last row of `banking_data`
bank_data
bank_data[-1]


array([   10, 33000,   410,  1450,    11])

In [ ]:
#**Q3.3:** Extract the Account_Balance column (column index 1)
bank_data
bank_data[0:11,1]

array([25000, 32000, 28000, 41000, 35000, 27000, 39000, 30000, 45000,
       33000])

In [ ]:
#**Q3.4:** Extract the first 4 rows and first 3 columns
bank_data[0:4,0:3]


array([[    1, 25000,   300],
       [    2, 32000,   450],
       [    3, 28000,   380],
       [    4, 41000,   500]])

In [ ]:
#**Q3.5:** Extract rows 3 to 7 (inclusive)
bank_data[0:7]


array([[    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18]])

In [ ]:
### Question 4: Mathematical Operations


In [ ]:
#**Q4.1:** Calculate the sum of all account balances
sum_account_bal=np.sum(bank_data[0:11,1])
print(f"sum:{sum_account_bal}")


sum:335000


In [ ]:
#**Q4.2:** Calculate the mean account balance
mean_account_bal=np.mean(bank_data[0:11,1])
print(f"mean:{mean_account_bal}")


mean:33500.0


In [ ]:
#**Q4.3:** Calculate the standard deviation of account balances
standard_deviation=np.std(bank_data[:,1])
print(f" standard deviation :{standard_deviation}")


 standard deviation :6168.468205316454


In [ ]:
#**Q4.4:** Calculate the variance of account balances
var_acc_bal=np.var(bank_data[:,1])
print(f" variance:{var_acc_bal}")

 variance:38050000.0


In [ ]:
#**Q4.5:** Calculate the median account balance
median_acc_bal=np.median(bank_data[:,1])
print(f" median: {mean_account_bal}")


 median: 33500.0


In [ ]:
### Question 5: Statistical Functions


In [ ]:
#**Q5.1:** Find the minimum and maximum account balances
minimum_acc_bal=np.max(bank_data[0:11,1])
maximum_acc_bal=np.min(bank_data[0:11,1])
print(f"minimum:{minimum_acc_bal}")
print(f"maximum:{maximum_acc_bal}")


minimum:45000
maximum:25000


In [ ]:
#**Q5.2:** Find the minimum and maximum credit scores
bank_data[0:11,2]
minimum_cre_sco=np.min(bank_data[0:11,2])
maximum_cre_sco=np.max(bank_data[0:11,2])
print(f"min:{minimum_cre_sco}")
print(f"max:{maximum_cre_sco}")

min:300
max:550


In [ ]:
#**Q5.3:** Calculate the percentile values for account balances (25th, 50th, 75th)
percentile=np.percentile(bank_data[:,1],[25,50,75])
print(f"25th:{percentile[0]}")
print(f"50th:{percentile[1]}")
print(f"75th:{percentile[2]}")


25th:28500.0
50th:32500.0
75th:38000.0


In [ ]:
# **Q5.4:** Calculate the correlation between account balance and credit score
bank_data
acc_bal=bank_data[:,1]
cre_score=bank_data[:,2]
corr=np.correlate(acc_bal,cre_score)
print(corr)

[146460000]


In [ ]:
# **Q5.5:** Calculate the covariance between account balance and credit score
bank_data
covariance=np.cov(bank_data[:,1],bank_data[:,2])[0,1]
print(covariance)

453888.8888888889


In [ ]:
# **Q6.1:** Reshape the `banking_data` to 5 rows × 10 columns
reshape=bank_data.reshape(5,10)
print(reshape)

[[    1 25000   300  1200    10     2 32000   450  1500    15]
 [    3 28000   380  1100     8     4 41000   500  1600    20]
 [    5 35000   420  1400    12     6 27000   360  1300     9]
 [    7 39000   480  1700    18     8 30000   400  1250    14]
 [    9 45000   550  1800    25    10 33000   410  1450    11]]


In [ ]:
# **Q6.2:** Flatten the `banking_data` to a 1D array
flatten=bank_data.flatten()
print(flatten)

[    1 25000   300  1200    10     2 32000   450  1500    15     3 28000
   380  1100     8     4 41000   500  1600    20     5 35000   420  1400
    12     6 27000   360  1300     9     7 39000   480  1700    18     8
 30000   400  1250    14     9 45000   550  1800    25    10 33000   410
  1450    11]


In [ ]:
# **Q6.3:** Transpose the `banking_data`
transpose=bank_data.transpose()
print(transpose)

[[    1     2     3     4     5     6     7     8     9    10]
 [25000 32000 28000 41000 35000 27000 39000 30000 45000 33000]
 [  300   450   380   500   420   360   480   400   550   410]
 [ 1200  1500  1100  1600  1400  1300  1700  1250  1800  1450]
 [   10    15     8    20    12     9    18    14    25    11]]


In [ ]:
# **Q6.4:** Split the `banking_data` into 2 equal parts vertically
bank_data
split_ver=np.vsplit(bank_data,2)    # bank_data,2 will split in two parts 0 and 1
print(split_ver[0])
print(split_ver[1])

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]]
[[    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [ ]:
# **Q6.5:** Split the `banking_data` into 2 equal parts horizontally
bank_data
split_hor=np.hsplit(bank_data,2) ######################################################################

ValueError: array split does not result in an equal division

In [ ]:
### Question 7: Logical Operations and Filtering


In [ ]:
# **Q7.1:** Find customers with account balance greater than $100,000
bank_data 
greater=bank_data[bank_data[:,1]>100000]
print(greater)

[[     1 125000    300     12     10]
 [     3 628000    380     11      8]
 [     5 935000    820     14     12]
 [     6 227000    360     13      9]
 [     8 730000    900     12     14]
 [    10 433000    810     19     11]]


In [ ]:
# **Q7.2:** Find customers with credit score greater than 800
# bank_data
# credit_score=bank_data[bank_data[:,2]>800]
# print(cre_score)
A=bank_data[bank_data[:,2]>800]
A


array([[     5, 935000,    820,     82,     12],
       [     8, 730000,    900,     31,     14],
       [    10, 433000,    810,     10,     11]])

In [ ]:
# **Q7.3:** Find customers with transaction count greater than 50 AND credit score less than 750
bank_data
tran=bank_data[:,3].mean()
cre_score=bank_data[:,2].mean()
data=bank_data[(bank_data[:,3]>tran) & (bank_data[:,2]<750)]
print(data)

[[     1 125000    300    120     10]
 [     2   3320    450     75     15]
 [     7  53000    480     92     18]
 [     9  84500    550     98     25]]


In [ ]:
# **Q7.4:** Count how many customers have account balance between $10,000 and $100,000

print(bank_data)
data=np.sum([(bank_data[:,1]>=10000) & (bank_data[:,1]<=100000)])
print(data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]
10


In [ ]:
# **Q7.5:** Find the index of the customer with the highest credit score
index=bank_data[:,2].argmax()+1
print(index)

8


In [ ]:
### Question 8: Sorting and Searching


In [ ]:
# **Q8.1:** Sort the `banking_data` by account balance (ascending)
print(bank_data)
sort=bank_data[:,1].argsort()
print(sort)


[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]
[0 5 2 7 1 9 4 6 3 8]


In [ ]:
# **Q8.2:** Sort the `banking_data` by credit score (descending)

descending=bank_data[-bank_data[:,2].argsort()]
print(descending)

[[    1 25000   300  1200    10]
 [    6 27000   360  1300     9]
 [    9 45000   550  1800    25]
 [    4 41000   500  1600    20]
 [    2 32000   450  1500    15]
 [    7 39000   480  1700    18]
 [   10 33000   410  1450    11]
 [    5 35000   420  1400    12]
 [    8 30000   400  1250    14]
 [    3 28000   380  1100     8]]


In [ ]:
# **Q8.3:** Find the indices that would sort the array by years active
year_active=bank_data[:,4].argsort()
print(year_active)

[2 5 0 9 4 7 1 6 3 8]


In [ ]:
# **Q8.4:** Find the customer with the second highest account balance
sec_hig_ind=np.argsort(bank_data[:,2])[-2]
sec_hig=bank_data[sec_hig_ind]
print(sec_hig[0])



4


In [ ]:
# **Q8.5:** Find the customer with the lowest transaction count
data=np.argmin(bank_data[:,3])
data1=bank_data[data]
print(data1[0])

3


In [ ]:
bank_data

array([[    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]])

In [26]:
# **Q9.1:** Calculate the absolute values of all elements
absolut=np.abs(bank_data[:])
print(absolut)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [ ]:
# **Q9.2:** Calculate the square root of all account balances
import math
root_square=np.sqrt(bank_data[:,1])
print(root_square)

[158.11388301 178.8854382  167.33200531 202.48456731 187.08286934
 164.31676725 197.48417658 173.20508076 212.13203436 181.65902125]


In [ ]:
# **Q9.3:** Calculate the square of all credit scores
square=np.square(bank_data[:,2])
print(square)

[ 90000 202500 144400 250000 176400 129600 230400 160000 302500 168100]


In [ ]:
# **Q9.4:** Calculate the exponential of all transaction counts
exponential=np.exp(bank_data[:,4])
print(exponential)

[2.20254658e+04 3.26901637e+06 2.97995799e+03 4.85165194e+08
 1.62753791e+05 8.10208393e+03 6.56599681e+07 1.20260328e+06
 7.20048993e+10 5.98731417e+04]


In [ ]:
# **Q9.5:** Calculate the natural logarithm of all account balances
logarithm=np.log(bank_data[:,1])
print(logarithm)

[10.1266311  10.37349118 10.23995979 10.62132735 10.46310334 10.20359214
 10.57131693 10.30895266 10.71441777 10.40426284]


In [ ]:
### Question 10: Advanced Operations


In [29]:
# **Q10.1:** Calculate the cumulative sum of account balances
cumulative=np.cumsum(bank_data[:,1])
print(cumulative)

[ 25000  57000  85000 126000 161000 188000 227000 257000 302000 335000]


In [30]:
# **Q10.2:** Calculate the cumulative product of transaction counts
cumulative_product=np.cumprod(bank_data[:,1])
cumulative_product

array([               25000,            800000000,       22400000000000,
         918400000000000000, -8674920475748466688, -4543341318423707648,
        9112153529354551296,  2305452334693482496,   866390664194031616,
       -1561395846761676800])

In [37]:
# **Q10.3:** Calculate the difference between consecutive account balances
consecutive=np.diff(bank_data[:,2])
consecutive

array([ 150,  -70,  120,  -80,  -60,  120,  -80,  150, -140])

In [39]:
# **Q10.4:** Calculate the gradient of account balances
gradient=np.gradient(bank_data[:,1])
print(gradient)

[  7000.   1500.   4500.   3500.  -7000.   2000.   1500.   3000.   1500.
 -12000.]


In [47]:
# **Q10.5:** Calculate the histogram of account balances with 5 bins
acc_bal,bin_data=np.histogram(bank_data[:,1], bins=5)
print(acc_bal)
print(bin_data)

[3 2 2 1 2]
[25000. 29000. 33000. 37000. 41000. 45000.]


In [49]:
# ## Question 11: Random Numbers and Simulation
# **Q11.1:** Generate 6 random integers between 1 and 1000
data=np.random.randint(1,1000,6)
print(data)

[504 828  73  24 539 343]


In [54]:
# **Q11.2:** Generate 6 random floats between 0 and 1
data=np.random.random(6)
print(data)

[0.93765191 0.70202359 0.35494405 0.92879688 0.16227721 0.73384393]


In [ ]:
# **Q11.3:** Generate 6 random numbers from normal distribution (mean=700, std=100)
data=np.random.normal(700,100,6)# first ps is mean and second ps is std
data

array([392.11880644, 708.90668307, 657.81912384, 704.83250414,
       896.30024356, 640.78235271])

In [ ]:
# **Q11.4:** Shuffle the `banking_data` rows randomly
bank_data
shuffle_data=bank_data.copy()
np.random.shuffle(shuffle_data)  # shuffle is there in np.random
print(shuffle_data)

[[   10 33000   410  1450    11]
 [    7 39000   480  1700    18]
 [    9 45000   550  1800    25]
 [    6 27000   360  1300     9]
 [    1 25000   300  1200    10]
 [    8 30000   400  1250    14]
 [    3 28000   380  1100     8]
 [    2 32000   450  1500    15]
 [    5 35000   420  1400    12]
 [    4 41000   500  1600    20]]


In [ ]:
# **Q11.5:** Set random seed to 123 and generate 4 random numbers
np.random.seed(123)
seeded_random=np.random.random(4)
print(seeded_random)



[0.37454012 0.95071431 0.73199394]


In [ ]:
### Question 12: Linear Algebra Operations


In [83]:
# **Q12.1:** Calculate the dot product of account balance and credit score columns
bank_data
a=bank_data[:,1]
b=bank_data[:,2]
the_dot_product=np.dot(a,b)
print(the_dot_product)


146460000


In [6]:
# **Q12.2:** Calculate the cross product of first two rows
cross_product=np.cross(bank_data[0],bank_data[1])
cross_product

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [ ]:
# **Q12.3:** Calculate the norm (magnitude) of the account balance column
data=np.linalg.norm(bank_data[:,1])
print(data)

107717.22239270747


In [121]:
# **Q12.4:** Create a 3x3 matrix and calculate its determinant
data=np.random.randint(0,10,(3,3))
print(data)
print(np.ndim(data))


[[7 0 7]
 [7 2 0]
 [7 2 2]]
2


In [119]:
# **Q12.5:** Calculate the inverse of the 3x3 matrix
print(data)
data1=np.invert(data)
print(data1)

[[1 9 3]
 [7 6 8]
 [7 4 1]]
[[ -2 -10  -4]
 [ -8  -7  -9]
 [ -8  -5  -2]]


In [ ]:
### Question 13: String Operations


In [143]:
# **Q13.1:** Convert all customer IDs to strings
bank_data
a=(bank_data[:,0]).astype(str)
a


array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

In [144]:
# **Q13.2:** Check if any customer ID contains '100'
bank_data[:,0]
contains_100=np.char.find(a,'100')>=0
print(contains_100)


[False False False False False False False False False False]


In [147]:
# **Q13.3:** Convert all customer IDs to uppercase (if they were strings)
customer_uppercase=np.char.upper(a)
print(customer_uppercase)


['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


In [152]:
# **Q13.4:** Count the length of each customer ID string
len_custome=np.char.str_len(a)
print(len_custome)

[1 1 1 1 1 1 1 1 1 2]


In [160]:
# **Q13.5:** Replace '100' with 'CUST' in customer IDs
replace_100=np.char.replace(a,2,new='CUST')
print(replace_100)


['1' 'CUST' '3' '4' '5' '6' '7' '8' '9' '10']


In [ ]:
### Question 14: Date and Time Operations


In [7]:
# **Q14.1:** Convert years active to months
year_to_months=bank_data[:,4]*12
print(year_to_months)

[120 180  96 240 144 108 216 168 300 132]


In [ ]:
# **Q14.2:** Calculate the average years active
bank_data
avarage_year_active=np.average(bank_data[:,4])
print(avarage_year_active)




14.2


In [ ]:
# **Q14.3:** Find customers who have been active for more than 5 years

active_5=bank_data[bank_data[:,4]>5]
print(active_5)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [19]:
# **Q14.4:** Calculate the total time all customers have been active (in years)
bank_data
total_active=np.sum(bank_data[:,4])
print(total_active)

142


In [24]:
# **Q14.5:** Find the customer with the shortest time active
bank_data
shortest_time=np.sort(bank_data[:,4])
print(shortest_time[0])

8


In [ ]:
### Question 15: Advanced Array Operations


In [32]:
# **Q15.1:** Apply a function to calculate 5% interest on all account balances
print(bank_data[:,1])
interest=[]
acc_bal=bank_data[:,1]
for i in acc_bal:
    z=(acc_bal*0.05)
    interest=z+acc_bal
print(z)
print(interest)


[25000 32000 28000 41000 35000 27000 39000 30000 45000 33000]
[1250. 1600. 1400. 2050. 1750. 1350. 1950. 1500. 2250. 1650.]
[26250. 33600. 29400. 43050. 36750. 28350. 40950. 31500. 47250. 34650.]


In [39]:
# **Q15.2:** Use `np.where` to categorize customers by balance ranges
range_customer=np.where(bank_data[:,1]>39000,"high","lower")
print(range_customer)

['lower' 'lower' 'lower' 'high' 'lower' 'lower' 'lower' 'lower' 'high'
 'lower']
