In [168]:
# # Retail Data – Business Questions (for `retail_data`)

# **Assumed columns:** `[StoreID, Sales, Customers, Inventory, Returns]`

# ## Basic Performance Analysis
# 1. What is the **total revenue** generated across all stores?
# 2. Which store recorded the **highest sales**?
# 3. Which store recorded the **lowest sales**?
# 4. What is the **average daily sales** per store?
# 5. How many stores achieved sales **above ₹35,000**?

# ## Customer Insights
# 6. Which store had the **highest customer footfall**?
# 7. What is the **average number of customers** per store?
# 8. How many stores have **more than 450 customers**?
# 9. Which store has the **lowest customer count**?
# 10. Is there any store where **high sales do not correspond to high customers**?

# ## Inventory & Returns Analysis
# 11. What is the **total inventory** across all stores?
# 12. Which store has the **highest inventory stock**?
# 13. How many stores have **inventory less than 1300 units**?
# 14. Which store has the **highest return rate** (returns ÷ inventory)?
# 15. Which stores have **returns greater than 15 units**?

# ## Sales & Customer Correlation
# 16. Is there a **positive correlation** between sales and customers?
# 17. Which store has **high customer visits but low sales**?
# 18. Which store has **low customers but high sales**?
# 19. How many stores have **sales per customer above ₹90**?
# 20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?

# ## Profitability & Growth
# 21. If profit margin is **20% of sales**, what is the **profit per store**?
# 22. Which store has the **highest profit**?
# 23. Which store has the **lowest profit**?
# 24. If sales increase by **10% next month**, what are the **new sales figures**?
# 25. How will **total profit** change with the 10% sales increase?

# ## Operational Strategy
# 26. Which stores need **inventory restocking** based on sales and current stock?
# 27. Which stores show **high returns percentage** and might require **quality checks**?
# 28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
# 29. Which store is the **worst performer overall**?
# 30. Which stores can be considered for **expansion** based on strong sales and customer metrics?

In [169]:
# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
import numpy as np
store_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

In [170]:
store_data

array([[    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]])

In [188]:
# 1. What is the **total revenue** generated across all stores?
revenue=sum(store_data[:,4])
print(f"the total revenue:{revenue}")


the total revenue:142


In [172]:
# 2. Which store recorded the **highest sales**?
print(store_data)
highest_sales=np.argmax(store_data[0:11,1])+1
print(f"highest sales:{highest_sales}")

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]
highest sales:9


In [173]:
# 3. Which store recorded the **lowest sales**?

print(store_data)
lowest_sales=np.argmin(store_data[0:11,1])+1
print(f"lowest sales:{lowest_sales}")

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]
lowest sales:1


In [174]:
# 4. What is the **average daily sales** per store?
store_data
average_daily_sales=np.mean(store_data[:,1]/10)
print(f"average_daily_sales:{average_daily_sales}")

average_daily_sales:3350.0


In [175]:
# 5. How many stores achieved sales **above ₹35,000**?

sales=store_data[store_data[:,1]>35000]
print(f"stores achieved sales **above ₹35,000**:{(sales)}")

stores achieved sales **above ₹35,000**:[[    4 41000   500  1600    20]
 [    7 39000   480  1700    18]
 [    9 45000   550  1800    25]]


In [176]:
# 6. Which store had the **highest customer footfall**?
store_data
high_customer=np.argmax(store_data[:,2])+1
print(f"highest customer footfall:{high_customer}")

highest customer footfall:9


In [177]:
# 7. What is the **average number of customers** per store?
ava_cust=(np.mean(store_data[:,2]/10))
print(f"average number of customers:{ava_cust}")

average number of customers:42.5


In [190]:
# 8. How many stores have **more than 450 customers**?
more=store_data[store_data[:,2]>450]
print(f"stores have **more than 450 customers:{more.shape}")

stores have **more than 450 customers:(3, 5)


In [179]:
# 9. Which store has the **lowest customer count**?
low=store_data[:,2].argmin()+1
print(f"lowest customer count in store:{low}")

lowest customer count in store:1


In [197]:
# 10. Is there any store where **high sales do not correspond to high customers**?
print(store_data)
sales=store_data[:,1].mean()
cutomers=store_data[:,2].mean()
data=store_data[(store_data[:,1]>sales) & (store_data[:,2]<cutomers)]
data

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


array([[    5, 35000,   420,  1400,    12]])

In [181]:
# 11. What is the **total inventory** across all stores?
inventory=sum(store_data[:,3])
print(f"total inventory:{inventory}")

total inventory:14300


In [182]:
# 12. Which store has the **highest inventory stock**?
print(store_data)
inventory=store_data[:,3].max()
print(f"highest inventory:{inventory}")

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]
highest inventory:1800


In [198]:
# 13. How many stores have **inventory less than 1300 units**?
inventory=store_data[store_data[:,3]<1300]
print(f"inventory less than 1300 units:{inventory.shape}")

inventory less than 1300 units:(3, 5)


In [184]:
# 14. Which store has the **highest return rate** (returns ÷ inventory)?
store_data
rate=np.argmax([(store_data[:,4])/(store_data[:,3])])+1
print(f"highest return rate:{rate}")

highest return rate:9


In [185]:
# 15. Which stores have **returns greater than 15 units**?
untis=store_data[store_data[:,4]>15]
print(f"returns greater than 15 units:{untis}")

returns greater than 15 units:[[    4 41000   500  1600    20]
 [    7 39000   480  1700    18]
 [    9 45000   550  1800    25]]


In [186]:
# 16. Is there a **positive correlation** between sales and customers?
sales=store_data[:,1]
cutomers=store_data[:,2]
corr=np.corrcoef(sales/cutomers)
print(f"it is a storng correlation:{corr}")

it is a storng correlation:1.0


In [199]:
# 17. Which store has **high customer visits but low sales**?
print(store_data)
cutomers=store_data[:,2].mean()
sales=store_data[:,1].mean()
data=store_data[(store_data[:,2]>cutomers) & (store_data[:,1]<sales)]
data

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


array([[    2, 32000,   450,  1500,    15]])

In [201]:
# 18. Which store has **low customers but high sales**?
print(store_data)
cutomers=store_data[:,2].mean()
sales=store_data[:,1].mean()
data=store_data[(store_data[:,2]<cutomers) & (store_data[:,1]>sales)]
data


[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


array([[    5, 35000,   420,  1400,    12]])

In [ ]:
# 19. How many stores have **sales per customer above ₹90**?
print(store_data)
store=store_data[:,1]/store_data[:,2]
A=store_data[store>90]
print(A)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]
[]


In [202]:
# 20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?
cutomers=store_data[:,2].mean()
inventory=store_data[:,3].mean()
data=store_data[(store_data[:,2]<cutomers)&(store_data[:,3]>inventory)]
data


array([[   10, 33000,   410,  1450,    11]])

In [203]:
# 21. If profit margin is **20% of sales**, what is the **profit per store**?
sales=store_data[:,1]*0.2
sales

array([5000., 6400., 5600., 8200., 7000., 5400., 7800., 6000., 9000.,
       6600.])

In [ ]:
# 22. Which store has the **highest profit**?
profit=np.argmax(store_data[:,1]*0.2)+1
sales

np.int64(9)

In [207]:
# 23. Which store has the **lowest profit**?
profit=np.argmin(store_data[:,1]*0.2)+1
profit

np.int64(1)

In [ ]:
# 24. If sales increase by **10% next month**, what are the **new sales figures**?
increase=store_data[:,1]+(store_data[:,1]*0.1)
print(increase)

[27500. 35200. 30800. 45100. 38500. 29700. 42900. 33000. 49500. 36300.]


In [208]:
# 25. How will **total profit** change with the 10% sales increase?
increase=sum(store_data[:,1]+(store_data[:,1]*0.1))
increase

np.float64(368500.0)

In [211]:
# 26. Which stores need **inventory restocking** based on sales and current stock?
sales=store_data[:,1].mean()
inventory=store_data[:,3].mean()
store_id=store_data[:,0]
inventory_restocking=store_id[(store_data[:,1]>sales) &(store_data[:,3])<inventory]
inventory_restocking


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# 27. Which stores show **high returns percentage** and might require **quality checks**?


In [ ]:
# 28. Which store is the **best performer overall** (sales, customers, inventory turnover)?


In [ ]:
# 29. Which store is the **worst performer overall**?
store_id=store_data[:,0]
sales=store_data[:,1]
cutomers=store_data[:,2]
inventory_restocking